### ISSUE TITLE
feature request: upload to basic auth protected environment

### ISSUE THREAD

**Issue by latica-jp** [kintone/plugin-uploader#298]
Hello,

We recognize that this uploader lacks the ability to upload plugins to a basic authentication protected environment.

We want to use this uploader for basic auth protected environments, so we're requesting an upgrade.

Thanks in advance.

**Comment by koba04** [comment]
@latica-jp 
Thank you for your feedback! That makes sense to me so we'll consider adding the feature.

**Comment by koba04** [comment]
@latica-jp 
We've just released a new version including the basic authentication support!
https://github.com/kintone/plugin-uploader/blob/master/CHANGELOG.md#410-2020-06-22
Thank you for reporting!!!

**Comment by latica-jp** [comment]
@koba04 

Glad to hear that! Thanks for your effort!
